defaults: &defaults
  app_name: "groupme1"
  #domain: "http://groupme1.dev"    
  domain: "http://localhost:3000"
  facebook_app_id: 
  facebook_secret: 
  hipchat_token: 
  hipchat_room_name: 
  admin_emails: 
    - ""
  google_analytics_key: ""
  default_logo_url: "/logo.png"
  email_sender: ""
  github_key: 
  github_secret: 

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
